//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookChatbotManagement.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatbotEntities : DbContext
    {
        public ChatbotEntities()
            : base("name=ChatbotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dialog> Dialogs { get; set; }
        public virtual DbSet<DialogIntentMapping> DialogIntentMappings { get; set; }
        public virtual DbSet<DialogStep> DialogSteps { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Intent> Intents { get; set; }
        public virtual DbSet<IntentPatternMapping> IntentPatternMappings { get; set; }
        public virtual DbSet<PatternEntityMapping> PatternEntityMappings { get; set; }
        public virtual DbSet<Pattern> Patterns { get; set; }
    }
}
