//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacebookChatbotManagement.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialogStep
    {
        public int Id { get; set; }
        public int DialogId { get; set; }
        public int Step { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}
